[package]
name = "rust-rltk-roguelike-tutorial"
version = "0.1.0"
authors = ["Max Whitney <mwhitney@alumni.sfu.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.8.1" }
